name: llava
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=1.1.1w=h7f8727e_0
  - python=3.10.0=h12debd9_5
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py310h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.21.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - altair==5.5.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bitsandbytes==0.45.3
      - cachetools==5.5.2
      - certifi==2022.12.7
      - cffi==1.17.1
      - charset-normalizer==2.1.1
      - click==8.1.8
      - contourpy==1.3.1
      - cryptography==43.0.3
      - cycler==0.12.1
      - datasets==3.5.0
      - deepspeed==0.12.6
      - dill==0.3.8
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - exceptiongroup==1.2.2
      - fastapi==0.115.11
      - ffmpy==0.5.0
      - filelock==3.13.1
      - flash-attn==2.5.2
      - fonttools==4.56.0
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - git-lfs==1.6
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-api-python-client==2.168.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.2
      - googleapis-common-protos==1.70.0
      - gradio==4.16.0
      - gradio-client==0.8.1
      - h11==0.14.0
      - hjson==3.1.0
      - httpcore==0.17.3
      - httplib2==0.22.0
      - httpx==0.24.0
      - huggingface-hub==0.29.3
      - idna==3.4
      - importlib-resources==6.5.2
      - jinja2==3.1.4
      - jiter==0.9.0
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - latex2mathml==3.77.0
      - levenshtein==0.27.1
      - llava==1.2.2.post1
      - markdown-it-py==3.0.0
      - markdown2==2.5.3
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.4.3
      - multiprocess==0.70.16
      - narwhals==1.30.0
      - networkx==3.3
      - ninja==1.11.1.3
      - numpy==1.26.4
      - nvidia-ml-py==12.570.86
      - oauthlib==3.2.2
      - openai==1.75.0
      - opencv-python==4.11.0.86
      - orjson==3.10.15
      - packaging==24.2
      - pandas==2.2.3
      - peft==0.10.0
      - pillow==10.4.0
      - pip==25.0.1
      - platformdirs==4.3.6
      - propcache==0.3.1
      - proto-plus==1.26.1
      - protobuf==5.29.3
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pynvml==12.0.0
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-multipart==0.0.20
      - pytz==2025.1
      - pyyaml==6.0.2
      - rapidfuzz==3.13.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==13.9.4
      - rpds-py==0.23.1
      - rsa==4.9.1
      - ruff==0.11.0
      - safetensors==0.5.3
      - scikit-learn==1.2.2
      - scipy==1.15.2
      - semantic-version==2.10.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.22.0
      - setproctitle==1.3.5
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - starlette==0.46.1
      - svgwrite==1.4.3
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - timm==0.6.13
      - tokenizers==0.15.1
      - tomlkit==0.12.0
      - torch==2.1.2+cu121
      - torchaudio==2.1.2+cu121
      - torchvision==0.16.2+cu121
      - tqdm==4.67.1
      - transformers==4.37.2
      - triton==2.1.0
      - typer==0.15.2
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uritemplate==4.1.1
      - urllib3==1.26.13
      - uvicorn==0.34.0
      - volcengine-python-sdk==1.1.5
      - wandb==0.19.8
      - wavedrom==2.0.3.post3
      - websockets==11.0.3
      - word2number==1.1
      - xxhash==3.5.0
      - yarl==1.20.0
prefix: /home/exouser/miniconda3/envs/llava
